a,b,c=map(float, input().split())
print("TRIANGULO: %.3f"%((a*c)/2))
print("CIRCULO: %.3f"%(c**2*3.14159))
print("TRAPEZIO: %.3f"%(((a+b)*c)/2))
print("QUADRADO: %.3f"%(b**2))
print("RETANGULO: %.3f"%(a*b))